### ISSUE TITLE
Version number conflict causing deployment failure

### ISSUE THREAD

**Issue by MarcHartwig13** [verbb/tablemaker#14]
Linode server, set up with forge with auto-deploy on.

Received this error after updating TableMaker to 2.0.1 on my local version of the site (EDIT: And then attempted to deploy to the linode server):

`
Problem 1     - The requested package supercool/tablemaker 2.0.1 exists as supercool/tablemaker[2.0.0, dev-master] but these are rejected by your constraint.
`

At the time of writing, packagist reads 2.0.0 as latest version number.

`2.0.0 2018-04-12 10:56 UTC`
Link: https://packagist.org/packages/supercool/tablemaker

But Github is at 2.0.1 
Link: https://github.com/supercool/tablemaker/blob/master/CHANGELOG.md

Possible conflict creating deployment issue? I just rolled back to 2.0.0 for the time being.

Thanks!

**Comment by mmikkel** [comment]
Yep, it appears that the latest 2.0.1 release hasn't been published to Packagist.

@Nav33d If the auto-publishing doesn't work (might be an issue w/ the GitHub integration?), it's possible to log into Packagist and manually hit "Update" for the package.

**Comment by Nav33d** [comment]
@MarcHartwig13 @mmikkel Thank you for letting me know. I have updated the version on Packagist. I will take a look at setting up the auto update
