### ISSUE TITLE
Use TableMaker with GraphQL

### ISSUE THREAD

**Issue by TobiasDax** [verbb/tablemaker#15]
We've been encountering some issues while hooking up `tablemaker` to [CraftQL](https://github.com/markhuot/craftql). In particular, we've been unable to read row/column data from the `table` field of our content type. Instead, our query throws this error:
```json
{
    "error": "String cannot represent non scalar value: associative array(3) with first keys: \"columns\", \"rows\", \"table\""
}
```
Is there anything that we can do about this?

**Comment by joshuarichard** [comment]
@engram-design why was [a PR for this](https://github.com/verbb/tablemaker/pull/19) closed a few weeks ago

**Comment by engram-design** [comment]
Ah, looks like due to deleting the `master` branch (in favour of `craft-3` and `craft-4`) closed the PR. I've just merged this manually for the next release. To get this early, change your `verbb/tablemaker` requirement in `composer.json` to:

Craft 3
```
"require": {
  "verbb/tablemaker": "dev-craft-3 as 3.0.1",
  "...": "..."
}
```

Craft 4
```
"require": {
  "verbb/tablemaker": "dev-craft-4 as 4.0.1",
  "...": "..."
}
```

Then run `composer update`.

**Comment by joshuarichard** [comment]
Thanks a ton @engram-design

**Comment by engram-design** [comment]
Added in [3.0.2](https://github.com/verbb/tablemaker/releases/tag/3.0.2) and [4.0.2](https://github.com/verbb/tablemaker/releases/tag/4.0.2)
