### ISSUE TITLE
Migration of existing Craft 2 table maker field type

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/tablemaker#16]
It doesn't look like the Craft 3 version handles existing Craft 2 Table Maker fields when coming from a migration. Is this something that could be possible?

In an existing Craft 2 project we use the Table Maker field within a body matrix block on various entries. It would be nice to have this data migrated.

Thanks,

**Comment by jamesmacwhite** [comment]
Looks like the Table Maker Craft 3 plugin is pretty much the same as the Craft 2 version data structure wise. For anyone coming from Craft 2, here's a content migration will update the field type for you:

https://gist.github.com/jamesmacwhite/02f23169d2967100cb0ce675d7e1a95e

**Comment by martinsmith** [comment]
Hello, how do I use the migration script?

**Comment by jamesmacwhite** [comment]
@martinsmith Is it a content migration

https://docs.craftcms.com/v3/extend/migrations.html

Content migrations are an extension of the migration feature in Craft 3.

**Comment by martinsmith** [comment]
Hi, i'm not sure?  In the CP I see this 
<img width="506" alt="image" src="https://user-images.githubusercontent.com/5725864/63345233-2f4bbe00-c34a-11e9-943b-157007ab279e.png">

**Comment by martinsmith** [comment]
On the front end I see "Impossible to access an attribute ("table") on a null variable."

**Comment by jamesmacwhite** [comment]
Content migrations need to be executed either via CI or manually through Craft CLI.

https://docs.craftcms.com/v3/extend/migrations.html#executing-migrations.

**Comment by martinsmith** [comment]
Thanks...  so I created a .php file containing your code on my desktop.  I've CD'd to my Craft project..  I entered ./craft migrate/up --plugin=tablemaker but I get -bash: ./craft: Permission denied.

**Comment by martinsmith** [comment]
Getting closer...  now getting "Invalid plugin handle: tablemaker"

**Comment by jamesmacwhite** [comment]
For content migrations, you don't specify the plugin, you can simply run:

./craft migrate/up or ./craft migrate/all

**Comment by martinsmith** [comment]
Sorry, this isn't working for me.  I get the following error in Terminal:

Exception 'craft\errors\DbConnectException' with message 'Craft CMS can’t connect to the database with the credentials in config/db.php.'

in /Users/Martin/Desktop/vic3/httpdocs/vendor/craftcms/cms/src/db/Connection.php:179

**Comment by jamesmacwhite** [comment]
At this point that's an error from Craft itself not related to anything with this plugin or the migration. Craft CLI cannot connect to the DB config specified. You might want to ask in the Craft Discord for further help, as this is Craft setup issue:

https://docs.craftcms.com/v3/
https://craftcms.com/community

**Comment by engram-design** [comment]
This is waaaay out of date now, but thanks to your own fixes @jamesmacwhite these have been rolled in for the next release.
