### ISSUE TITLE
Illegal string offset 'table'

### ISSUE THREAD

**Issue by sbextreme** [verbb/tablemaker#2]
This plugin is great! However I am having a random error appear.

I am occasionally getting the following error from the plugin:

Illegal string offset 'table' this is coming from the following line in the prepValue function: $value['table'] = TemplateHelper::getRaw($html);

It would appear the key can't be identified in the array, any ideas why this would be happening? 

I should point out I am using this field inside a matrix, if that would make a difference. 

Thanks,

Scott

**Comment by joshangell** [comment]
Hi Scott,

I'm not totally sure why that would be happening - what version of Craft and PHP are you running?

Josh

**Comment by sbextreme** [comment]
Hi Josh,

Thanks for getting back.

Craft version is  2.3.2644
PHP version is 5.5.17

I did just find something else....as the error stopped me getting to the entry in the CMS is added a check around the line:

		if (isset($value['table'])) {
			$value['table'] = TemplateHelper::getRaw($html);
		}

I then deleted the table, created another and saved the entry. The error then no longer appeared and I could view the table on my front end.

Sorry I'm not too familiar with the craft plugin architecture, when does the 'table' key get created? It seems very random as I have multiple entries with the same fields and some work and others don't.

Cheers,

Scott

**Comment by joshangell** [comment]
Ok - is it only happening with empty tables?

For example: create a block with a table field, make sure there are no rows then save it.

**Comment by sbextreme** [comment]
It worked fine with an empty table, I just get an empty table on the front end.

I've got around 40 'product' entries which use this and only 2 had the problem which I fixed by removing the table and adding a new one. 

I just had one idea, maybe the 2 broken entries were created before a craft update and all others were created after. I can't be sure I'll have a quick look at the creation dates.

Cheers,

Scott

**Comment by joshangell** [comment]
Good plan. I should probably add some more checks though so I'll do that anyway at some point.

**Comment by theskyfloor** [comment]
I am getting this error too on a Craft 2 site, did anyone every figure it out?

**Comment by engram-design** [comment]
Closing due to age, and we no longer support the Craft 2 version.
