### ISSUE TITLE
Justo to say thank you! Amazing plugin, nothing do what Tablemaker does!

### ISSUE THREAD

**Issue by zzseba78** [verbb/tablemaker#22]
Amazing plugin!

I need the content admin to be able to create tabulated data, but the column change from one entry to another, this plugin does exactly that, amazing! 

And works like a boss 😎 

Thank you, you have my 🌟

**Comment by engram-design** [comment]
Whilst we're the new owners of this plugin, I'm sure the Supercool team appreciated your thanks at the time!
