### ISSUE TITLE
Docs quality / missing / out of date

### ISSUE THREAD

**Issue by darylknight** [verbb/tablemaker#23]
Although the link in this repo to the docs works (http://plugins.supercooldesign.co.uk/plugin/table-maker/docs), that page says it requires Craft 2.3 and has only been tested on PHP 5.5. It's also missing any examples on how to use it.

**Comment by darylknight** [comment]
This is still the case 5 months later.

**Comment by engram-design** [comment]
No longer relevant due to new ownership/old issue.
