### ISSUE TITLE
Craft 4 Support

### ISSUE THREAD

**Issue by timeverts** [verbb/tablemaker#27]
We have several Craft 3 sites using your plugin and are really keen to upgrade them to Craft 4.

Do you have any plans to add support for Craft 4?

**Comment by sfsmfc** [comment]
@timeverts https://github.com/supercool/tablemaker/pull/26 ?

**Comment by timeverts** [comment]
Great to see there's some work there @sfsmfc. But will someone be merging that request into an official release for the plugin store, or am I talking to the wrong person about this?

**Comment by sfsmfc** [comment]
You are talking to the wrong person. I'm only a developer, who use this plugin and have searched for a solution...

**Comment by engram-design** [comment]
Just to chime in, we've added this to our [Craft 3 migration project](https://verbb.io/craft-3). If it gets enough votes, we'll migrate this plugin to Craft 4 and continue to work on it, giving it a new home, and keeping it open source.

Do let us know if you plan to make the plugin Craft 4 compatible!

**Comment by jamesmacwhite** [comment]
@engram-design Amazing if you do it! I see the votes were met on your site, will verbb.io be taking it over?

**Comment by jamesmacwhite** [comment]
Just out of interest has anyone tried to make contact with the agency behind this plugin: https://supercooldesign.co.uk/contact, the lack of responses on this GitHub repo probably confirms it, but as they look to still be an active developer as an agency we can try and get an official word?

**Comment by engram-design** [comment]
@jamesmacwhite I'll reach out to them shortly, but I was under the impression from https://github.com/supercool/buttonbox/issues/39#issuecomment-1125099539 that there were plans for their other plugins, but that might not be the case!

**Comment by jamesmacwhite** [comment]
@engram-design Ah didn't know they'd responded on another repo already. I wouldn't say this plugin has been active for years, the Craft 3 port was done, but it didn't even have Craft 2 to 3 migration handling, so there wasn't really a smooth translation path to begin with, unless you forked it or wrote content migrations instead.

Of course if they do plan to change to update it to Craft 4, that would be great, just good to know given Craft 3 hasn't really had much activity.

**Comment by engram-design** [comment]
We've recently acquired this from the Supercool team. Read our [blog post](https://verbb.io/blog/supercool-plugins-have-a-new-home) for more details.

**Comment by engram-design** [comment]
Available for [Craft 4 now](https://github.com/verbb/tablemaker/releases/tag/4.0.0)
