### ISSUE TITLE
Column settings in it's own Matrix Block tab

### ISSUE THREAD

**Issue by carlcs** [verbb/tablemaker#5]
It would be really nice, if Table Maker column settings could live in their own (Pimp My Matrix) Matrix Block tab. Configure in one tab, enter content in another!

**Comment by supercooljames** [comment]
+1 to that!
ᐧ

On 8 December 2015 at 10:58, carlcs <notifications@github.com> wrote:

> It would be really nice, if Table Maker column settings could live in
> their own (Pimp My Matrix) Matrix Block tab. Configure in one tab, enter
> content in another!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/supercool/Table-Maker/issues/5>.
>



-- 
James Coleman
*SUPERCOOL*

Branding  /  Print  /  Web

0121 233 2837
What's new on our website? Have a look: www.supercooldesign.co.uk

Office hours: Mon-Fri 8am - 4pm

Supercool Ltd
registered in england no: 5752015
vat registration no: 972 3546 02

**Comment by joshangell** [comment]
That would be nice but quite possibly a massive headache ... currently it is just a field type, to get this behaviour without writing code into the PMM core you would either need two field types that link to each other somehow or some other kind of magic I haven’t thought of.

I'll have a think!
